const $=s=>document.querySelector(s);let page='',selected=null,dirty=false,interactionMode=false;
const toast=m=>{const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)};
async function json(url,options){const r=await fetch(url,options);const data=await r.json();if(!r.ok)throw Error(data.error||'操作失败');return data}
async function loadPages(){const pages=await json('/api/pages');$('#pages').innerHTML=pages.map(p=>`<button class="page ${p.name===page?'active':''}" data-page="${p.name}">${p.name}</button>`).join('');document.querySelectorAll('.page').forEach(b=>b.onclick=()=>openPage(b.dataset.page));if(!page&&pages[0])openPage(pages[0].name)}
async function openPage(name){if(dirty&&!confirm('当前修改还没有保存，确定切换页面吗？'))return;page=name;dirty=false;$('#state').textContent='已加载';document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===name));const html=await fetch('/api/page/'+encodeURIComponent(name)).then(r=>r.text());const previewHtml=html.replace(/<head([^>]*)>/i,'<head$1><base href="/">');const frame=$('#preview');frame.srcdoc=previewHtml;frame.onload=()=>prepare(frame.contentDocument)}
function prepare(doc){selected=null;showEditor(null);doc.addEventListener('click',e=>{if(interactionMode){const link=e.target.closest?.('a');const href=link?.getAttribute('href')||'';if(link&&!/^(javascript:|#)/i.test(href)){e.preventDefault();e.stopPropagation();toast('请使用左侧页面列表切换页面')}return}e.preventDefault();e.stopPropagation();select(e.target)},true)}
function select(el){selected?.classList.remove('selected-admin');selected=el;selected.classList.add('selected-admin');showEditor(el)}
function showEditor(el){$('#empty').hidden=!!el;$('#editor').hidden=!el;if(!el)return;const tag=el.tagName.toLowerCase();$('#elementName').textContent=({img:'图片',a:'链接',h1:'大标题',h2:'标题',h3:'卡片标题',p:'段落'}[tag]||'内容块');$('#textValue').value=tag==='img'?(el.alt||''):el.textContent.trim();$('#imageValue').value=tag==='img'?el.getAttribute('src')||'':el.querySelector?.('img')?.getAttribute('src')||'';$('#linkValue').value=tag==='a'?el.getAttribute('href')||'':el.closest('a')?.getAttribute('href')||'';const card=el.closest('.card');$('#sizeValue').value=card?[...card.classList].filter(x=>x.startsWith('span')).join(' '):''}
function changed(){dirty=true;$('#state').textContent='有未保存修改'}
$('#textValue').oninput=e=>{if(!selected)return;if(selected.tagName==='IMG')selected.alt=e.target.value;else selected.textContent=e.target.value;changed()};
$('#imageValue').oninput=e=>{const img=selected?.tagName==='IMG'?selected:selected?.querySelector('img');if(img){img.setAttribute('src',e.target.value);changed()}};
$('#linkValue').oninput=e=>{const a=selected?.tagName==='A'?selected:selected?.closest('a');if(a){a.setAttribute('href',e.target.value);changed()}};
$('#sizeValue').onchange=e=>{const c=selected?.closest('.card');if(!c)return;[...c.classList].filter(x=>x.startsWith('span')).forEach(x=>c.classList.remove(x));e.target.value.split(' ').filter(Boolean).forEach(x=>c.classList.add(x));changed()};
$('#duplicate').onclick=()=>{const c=selected?.closest('.card');if(!c)return toast('请先选择一张卡片');const n=c.cloneNode(true);n.classList.remove('selected-admin');c.after(n);prepareNew(n);changed();toast('卡片已复制')};
function prepareNew(root){root.querySelectorAll('a').forEach(a=>a.onclick=e=>e.preventDefault())}
$('#remove').onclick=()=>{const c=selected?.closest('.card')||selected;if(c&&confirm('确定删除这个内容块吗？')){c.remove();selected=null;showEditor(null);changed()}};
$('#saveBtn').onclick=async()=>{if(!page)return;try{selected?.classList.remove('selected-admin');const doc=$('#preview').contentDocument;const base=doc.querySelector('base[href="/"]');base?.remove();const html='<!DOCTYPE html>\n'+doc.documentElement.outerHTML;if(base)doc.head.prepend(base);await json('/api/page/'+encodeURIComponent(page),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({html})});dirty=false;$('#state').textContent='刚刚已保存';toast('保存成功，原文件已备份');if(selected)selected.classList.add('selected-admin')}catch(e){toast(e.message)}};
$('#previewBtn').onclick=()=>page&&window.open('/'+page,'_blank');
document.querySelectorAll('.canvasbar [data-device]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.canvasbar [data-device]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const device=b.dataset.device;$('#deviceFrame').dataset.device=device;$('#viewportSize').textContent={phone:'390 px',tablet:'768 px',desktop:'自适应宽度'}[device];setTimeout(()=>$('#preview').contentWindow?.dispatchEvent(new Event('resize')),260)});
$('#modeToggle').onclick=()=>{interactionMode=!interactionMode;selected?.classList.remove('selected-admin');if(interactionMode){selected=null;showEditor(null)}const button=$('#modeToggle');button.textContent=interactionMode?'▶ 交互模式':'✦ 编辑模式';button.classList.toggle('interacting',interactionMode);$('#deviceFrame').classList.toggle('is-interacting',interactionMode);$('#state').textContent=interactionMode?'可操作页面；完成后切回编辑模式':dirty?'有未保存修改':'可点击内容进行编辑';toast(interactionMode?'现在可以操作页面按钮和动画':'现在可以点选页面内容')};
$('#newPage').onclick=async()=>{const title=prompt('新页面标题');if(!title)return;let name=prompt('文件名（例如 notes.html）','new-page.html');if(!name)return;if(!name.endsWith('.html'))name+='.html';try{await json('/api/page',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title,name})});await loadPages();openPage(name);toast('新页面已创建')}catch(e){toast(e.message)}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});loadPages().catch(e=>toast(e.message));
